/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Case({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/case.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Back_panel.geometry} material={materials['Body material']} scale={10} />
        <group scale={10}>
          <mesh geometry={nodes.Body001.geometry} material={materials['Body material']} />
          <mesh geometry={nodes.Body001_1.geometry} material={materials['Ambient light']} />
        </group>
        <mesh geometry={nodes.Down_plate.geometry} material={materials['Body material']} scale={10} />
        <mesh geometry={nodes.Front_panel.geometry} material={materials.FrontBackLogo} scale={10} />
        <mesh geometry={nodes.Grip_1.geometry} material={materials['Grip material']} scale={10} />
        <mesh geometry={nodes.Grip_2.geometry} material={materials['Grip material']} scale={10} />
        <mesh geometry={nodes.Left_panel.geometry} material={materials['Left panel material']} scale={10} />
        <mesh geometry={nodes.Line_1.geometry} material={materials['Grip material']} scale={10} />
        <mesh geometry={nodes.Line_2.geometry} material={materials['Grip material']} scale={10} />
        <mesh geometry={nodes.Right_panel.geometry} material={materials['Body material']} scale={10} />
        <mesh geometry={nodes.Screen.geometry} material={materials.Screen} position={[-0.01, 0, 0]} scale={10} />
        <mesh geometry={nodes.Screen_glass.geometry} scale={10}>
          <meshPhysicalMaterial roughness={0} transmission={1} thickness={0.01} attach="material" opacity={1} ior={1.5}/>
        </mesh>
        <mesh geometry={nodes.Up_plate.geometry} material={materials['Body material']} scale={10} />
      </group>
      <group position={[8.61, 3.03, 4.75]} rotation={[1.44, 0.13, -0.78]}>
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={32.27} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/case.gltf')
